services:
  trlbot:
    image: ghcr.io/ankbhatia19/trlbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BALLCHASING_TOKEN=${BALLCHASING_TOKEN}
      - BALLCHASING_GROUP=${BALLCHASING_GROUP}
      - REPORT_CHANNEL=${REPORT_CHANNEL}
    restart: unless-stopped
